[package]
name = "bitcoin-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
name = "bitcoin_ffi"

[dependencies]
bitcoin = "0.30.0"
uniffi = { version = "0.23.0", features = ["build"] }

[build-dependencies]
uniffi = { version = "0.23.0", features = ["build", "cli"] }
